release v.1.3.0 - adding new s3 nfs module
aws-ia/terraform-aws-storagegateway pull request #9
Opened 2023-02-08 20:33 UTC by prabirsekhri

-Adding nfs s3 nfs module. 
-Making domain creation block optional for NFS only file gateways.

2023-02-09 23:22 UTC, wellsiau-aws commented on modules/s3-nfs-share/main.tf
> +  tags = {
do we really need these tags?

2023-02-09 23:24 UTC, wellsiau-aws commented on modules/s3-nfs-share/variables.tf
> +  default     = "3600"
i wonder if there's a min-max value that can be added into validation?

2023-02-09 23:31 UTC, wellsiau-aws commented on modules/aws-sgw/main.tf
> +  create_smb_active_directory_settings = (var.join_smb_domain == true && length(var.domain_controllers) > 0 && length(var.domain_name) > 0 && length(var.domain_password) > 0 && length(var.domain_user
just nit pick
breaking this into smaller locals for each validation, and then combined it would help from readability standpoint.

2023-02-09 23:32 UTC, wellsiau-aws requested changes
see my comment, specific about the tags on the module `s3-nfs-share`

2023-02-14 20:56 UTC, wellsiau-aws submitted a review, later dismissed
LGTM

2023-02-17 19:01 UTC, sshvans approved these changes

2023-02-17 19:05 UTC, wellsiau-aws approved these changes
LGTM

2023-02-17 19:10 UTC, merged